const contentEN = {
    // Page Meta
    pageTitle: "Deconstructing Genius: An Analysis of The Nueva School",

    // Navigation
    navTitle: "Nueva Analysis",
    navPhilosophy: "Philosophy",
    navStem: "STEM",
    navAdmissions: "Admissions",
    navComparison: "Comparison",
    navDiy: "DIY Model",

    // Header
    headerTitle: "Deconstructing Genius",
    headerSubtitle: "An interactive analysis of The Nueva School's paradigm for gifted education, exploring how it became America's #1 STEM school by building a culture of creativity and compassion, not competition.",

    // Philosophy Section
    philosophyTitle: "The Blueprint: A Beloved Community",
    philosophyPillarsTitle: "The Three Pillars",
    pillar1Tab: "Design Thinking",
    pillar2Tab: "SEL",
    pillar3Tab: "Inquiry",
    
    pillar1Title: "Pillar 1: Design Thinking",
    pillar1Desc: "A human-centered problem-solving mindset. An iterative cycle: identify, prototype, feedback, test. The goal is for this process to become the 'way they think.'",
    pillar1EvidenceTitle: "Evidence: The I-Lab",
    pillar1EvidenceSub: "The Innovation Lab",
    pillar1EvidenceDesc: "A makerspace where students 'play, design, make.' 72% of students use the lab weekly for personal projects and advanced engineering.",

    pillar2Title: "Pillar 2: SEL",
    pillar2Desc: "A formal, required academic discipline. Empathy and perspective-taking are not ancillary; they are the foundation for collaboration and the 'empathy' stage of Design Thinking.",
    pillar2EvidenceTitle: "Evidence: Core Coursework",
    pillar2EvidenceSub: '"Science of Mind" & "Ethics"',
    pillar2EvidenceDesc: "Required Upper School classes that directly fuse the development of high emotional intelligence (EQ) with high IQ.",

    pillar3Title: "Pillar 3: Inquiry",
    pillar3Desc: "Harnessing intrinsic motivation as the 'engine for academic excellence.' Student-driven curriculum de-emphasizes GPA to create space for genuine curiosity.",
    pillar3EvidenceTitle: "Evidence: The Quest",
    pillar3EvidenceSub: "The Quest Program",
    pillar3EvidenceDesc: "A required, multi-year, self-directed research project where students pursue a personal passion with expert mentorship.",
    
    readFullAnalysisBtn: "Read Full Analysis",
    hideFullAnalysisBtn: "Hide Full Analysis",
    philosophyFullAnalysis: `<h4 class="font-serif text-xl mb-4 font-bold">Foundational Mission: Educating the "Gifted Learner"</h4><p class="mb-4">The Nueva School's entire operational and pedagogical framework is built upon a single, sharply defined premise: to serve the unique needs of "gifted learners". The school's mission is threefold: to "inspire passion for lifelong learning, foster social and emotional acuity, and develop the imaginative mind". This holistic approach is designed to nurture the whole child, recognizing that for gifted learners, emotional and creative development are not ancillary to but are integral to intellectual growth and well-being.</p><h4 class="font-serif text-xl mb-4 font-bold">The "Beloved Community" as an Educational Environment</h4><p class="mb-4">Central to the Nueva experience is the cultivation of a specific type of school culture, which Head of School Lee Fertig explicitly describes as a "beloved community". This term signifies a deliberate and foundational commitment to creating an environment that is "inclusive and compassionate, collectively embracing diverse perspectives". The purpose of this "beloved community" is to establish a profound sense of psychological safety. The school promises students a "safe space to ask questions, make mistakes, and enjoy the journey of learning".</p><h4 class="font-serif text-xl mb-4 font-bold">Signature Programs as Pedagogical Engines</h4><p>The philosophical pillars of a Nueva education are brought to life through a set of signature programs. The **Quest Program** represents the culmination of the school's commitment to student-driven, passion-based learning. The **Innovation Labs (I-Labs)** are the physical nexus where ideas become tangible. The **Writing & Research Center (WRC)** empowers students to become strong, discerning researchers and communicators.</p>`,

    // STEM Section
    stemTitle: "Anatomy of a STEM Powerhouse",
    stemRankingTitle: "Ranking Paradox",
    stemRank1: "#1 in America",
    stemRank1Source: "Source: Niche.com (2024)",
    stemRank1Desc: "Measures holistic experience, weighing parent/student reviews and college outcomes heavily.",
    stemRank2: "#191 in America",
    stemRank2Source: "Source: Newsweek (2020)",
    stemRank2Desc: "Measures traditional, standardized data like AP scores, which doesn't capture the post-AP model.",
    stemAdvantageTitle: '"Post-AP" Advantage',
    stemAdvantageDesc: "Instead of a standardized AP track, Nueva offers 200+ courses. Freshmen can take Multivariable Calculus; seniors can conduct graduate-level research.",
    tableCol1: "Typical Course",
    tableCol2: "Nueva Equivalent",
    tableRow1a: "AP Calculus BC",
    tableRow1b: "Differential Equations",
    tableRow2a: "AP Physics C",
    tableRow2b: "Quantum Physics",
    tableRow3a: "AP Biology",
    tableRow3b: "Drug Design",
    tableRow4a: "AP Computer Science",
    tableRow4b: "Advanced CS Projects",

    // Admissions Section
    admissionsTitle: "The Gauntlet: Forging an Innovator",
    admissionsGauntletTitle: "Admissions Gauntlet",
    gauntlet1Title: "1. Cognitive Baseline",
    gauntlet1Desc: "Wechsler IQ Assessment (130+ Score).",
    gauntlet2Title: '2. "Creative Project"',
    gauntlet2Desc: "Submit original work to show passion.",
    gauntlet3Title: "3. Analytical Skills",
    gauntlet3Desc: "Timed exercises to assess thinking.",
    gauntlet4Title: "4. Holistic Review",
    gauntlet4Desc: "Interviews and recommendations.",
    anatomyTitle: "Anatomy of a Student",
    anatomyDesc: "The process selects for traits that allow students to thrive in Nueva's ecosystem.",
    chartData: {
        labels: ['Intrinsic Motivation', 'Creative Confidence', 'Emotional Acuity', 'Collaborative Spirit'],
        datasets: [{ label: 'Student Profile', data: [30, 25, 25, 20], backgroundColor: ['#E9C46A', '#2A9D8F', '#F4A261', '#E76F51'], hoverOffset: 8, borderColor: '#2A363B', borderWidth: 4 }]
    },

    // Comparison Section
    comparisonTitle: "National Landscape",
    compTableH1: "Metric",
    compTableH2: "The Nueva School",
    compTableH3: "Phillips Exeter Academy",
    compTableH4: "TJHSST",
    compTableR1H: "Core Pedagogy",
    compTableR1C1: "Integrated Design Thinking, SEL, and inquiry-based learning.",
    compTableR1C2: "The Harkness Method: student-led, discussion-based Socratic dialogue.",
    compTableR1C3: "Structured, accelerated, lab-based curriculum with senior research project.",
    compTableR2H: "Environment",
    compTableR2C1: "Collaborative, compassionate, fostering intrinsic motivation.",
    compTableR2C2: "Intellectually rigorous, immersive, residential, centered on intense debate.",
    compTableR2C3: "Pre-professional, lab-centric, highly specialized, and focused.",
    compTableR3H: "Primary Skill",
    compTableR3C1: "Human-centered, creative innovation. A fusion of high EQ and IQ.",
    compTableR3C2: "Critical analysis and articulate argumentation through civil discourse.",
    compTableR3C3: "Advanced scientific and engineering research methodology.",
    compTableR4H: "Ideal Student",
    compTableR4C1: "A gifted, creative, systems-thinker who thrives on autonomy.",
    compTableR4C2: "An intellectually voracious student who thrives on rigorous debate.",
    compTableR4C3: "A student with a deep passion for a specific STEM field.",

    // DIY Section
    diyTitle: "Build Your Own Nueva",
    diyPillar1Title: "Pillar 1: Inquiry",
    diyPillar2Title: "Pillar 2: Design Thinking",
    diyPillar3Title: "Pillar 3: SEL",
    diyStrategy: "Strategy:",
    diyOnline: "Online Resources:",
    diyBayArea: "Bay Area Resources:",
    diyPillar1Strategy: "Replicate the \"Quest\" program by pursuing deep, student-driven projects and university-level coursework. Goal: create original work.",
    diyPillar1Online1: "Art of Problem Solving (AoPS): Rigorous, problem-based math curriculum. (Ages 10-18)",
    diyPillar1Online2: "Coursera / edX: University courses in specialized topics. (Ages 13+)",
    diyPillar1Online3: "Lumiere Education: Structured research program with PhD mentors. (High School)",
    diyPillar1Bay1: "UC Berkeley ATDP: Challenging summer courses. (Grades K-11)",
    diyPillar1Bay2: "Stanford Pre-Collegiate Studies: Deep dives into university-level topics. (High School)",
    diyPillar1Bay3: "California Academy of Sciences Internship: Authentic scientific research. (High School)",
    diyPillar2Strategy: "Replicate the I-Lab by finding opportunities to \"learn by doing\" and creating prototypes. Focus on hands-on creation and embracing failure.",
    diyPillar2Online1: "IDEO U: Online Design Thinking courses. (Motivated High Schoolers)",
    diyPillar2Online2: "Outschool: Project-based classes like 3D printing or Scratch. (Ages 3-18)",
    diyPillar2Online3: "iD Tech: Intensive tech camps to build a tangible project. (Ages 7-19)",
    diyPillar2Bay1: "The Exploratorium (SF): Tinkering Studio for hands-on invention. (All Ages)",
    diyPillar2Bay2: "The Crucible (Oakland): Industrial arts classes. (Ages 8-18)",
    diyPillar2Bay3: "Galileo Camps (Various): Summer camps focused on innovation. (Grades Pre-K - 10th)",
    diyPillar3Strategy: "Replicate the \"Beloved Community\" by seeking experiences that require teamwork and empathy. Goal: develop \"soft skills\" for collaboration.",
    diyPillar3Online1: "Synthesis: Team-based, game-based problem-solving. (Ages 8-14)",
    diyPillar3Online2: "Outschool: Live classes on debate or collaborative storytelling. (Ages 5-18)",
    diyPillar3Online3: "Model UN / Mock Trial: Online clubs for negotiation and public speaking. (Middle/High School)",
    diyPillar3Bay1: "American Conservatory Theater (SF): Acting classes to build confidence and empathy. (Ages 8-19)",
    diyPillar3Bay2: "Bay Area Debate Club (Various): Classes and tournaments for critical thinking. (Middle/High School)",
    diyPillar3Bay3: "SF-Marin Food Bank (SF): Volunteering for community awareness. (Ages 11+ with adult)",

    // Footer
    footerShareTitle: "Share This Analysis",
    footerTwitter: "Twitter",
    footerLinkedIn: "LinkedIn",
    footerCopy: "Copy Link",
    copySuccess: "LINK COPIED!",
    footerDisclaimer: "WEBSITE SYNTHESIZES DATA FROM \"THE NUEVA SCHOOL: AN ANALYTICAL DEEP DIVE\" REPORT. VIZ CREATED WITH CHART.JS/HTML/CSS. NO SVG/MERMAID JS USED."
};
