const contentZH = {
    // Page Meta
    pageTitle: "解构天才：Nueva 学校分析",

    // Navigation
    navTitle: "Nueva 分析",
    navPhilosophy: "教育理念",
    navStem: "STEM",
    navAdmissions: "招生",
    navComparison: "对比",
    navDiy: "DIY 模型",

    // Header
    headerTitle: "解构天才",
    headerSubtitle: "对 Nueva 学校天才教育范式的互动式分析，探讨它如何通过建立一种创造、同情而非竞争的文化，成为美国排名第一的 STEM 学校。",

    // Philosophy Section
    philosophyTitle: "教育蓝图：一个“挚爱社区”",
    philosophyPillarsTitle: "三大支柱",
    pillar1Tab: "设计思维",
    pillar2Tab: "社交情感学习",
    pillar3Tab: "探究式学习",

    pillar1Title: "支柱一：设计思维",
    pillar1Desc: "以人为本的解决问题思维模式。一个迭代循环：识别、原型、反馈、测试。目标是让这个过程内化为他们的“思维方式”。",
    pillar1EvidenceTitle: "实践证据：创新实验室",
    pillar1EvidenceSub: "创新实验室 (I-Lab)",
    pillar1EvidenceDesc: "一个让学生“玩耍、设计、创造”的创客空间。72% 的学生每周都会使用实验室进行个人项目和高级工程设计。",

    pillar2Title: "支柱二：社交情感学习",
    pillar2Desc: "一门正式的必修学科。同理心和换位思考不是辅助性的；它们是协作和设计思维“共情”阶段的基础。",
    pillar2EvidenceTitle: "实践证据：核心课程",
    pillar2EvidenceSub: "《心智科学》与《伦理学》",
    pillar2EvidenceDesc: "高中必修课程，旨在将高情商（EQ）和高智商（IQ）的发展直接融合。",

    pillar3Title: "支柱三：探究式学习",
    pillar3Desc: "将内在动机作为“卓越学术的引擎”。学生驱动的课程弱化 GPA，为真正的好奇心创造空间。",
    pillar3EvidenceTitle: "实践证据：Quest 项目",
    pillar3EvidenceSub: "Quest 项目",
    pillar3EvidenceDesc: "一个多年的必修自导研究项目，学生在专家指导下追求个人热情所在。",

    readFullAnalysisBtn: "阅读完整分析",
    hideFullAnalysisBtn: "隐藏完整分析",
    philosophyFullAnalysis: `<h4 class="font-serif text-xl mb-4 font-bold">基本使命：教育“天才学习者”</h4><p class="mb-4">Nueva 学校的整个运营和教学框架都建立在一个明确的前提之上：服务于“天才学习者”的独特需求。学校的使命有三方面：“激发终身学习的热情，培养社交和情感敏锐度，并发展想象力丰富的头脑”。这种整体方法旨在培养整个孩子，认识到对于天才学习者来说，情感和创造力的发展不是附属的，而是智力成长和福祉的组成部分。</p><h4 class="font-serif text-xl mb-4 font-bold">作为教育环境的“挚爱社区”</h4><p class="mb-4">Nueva 体验的核心是培养一种特定类型的学校文化，校长李·费尔蒂格（Lee Fertig）明确地将其描述为“挚爱社区”。这个术语标志着一种深思熟虑和基础性的承诺，即创造一个“包容和富有同情心，共同拥抱不同观点”的环境。这个“挚爱社区”的目的是建立一种深刻的心理安全感。学校向学生承诺一个“可以安全地提问、犯错并享受学习旅程的空间”。</p><h4 class="font-serif text-xl mb-4 font-bold">作为教学引擎的标志性项目</h4><p>Nueva 教育的哲学支柱通过一系列标志性项目得以实现。**Quest 项目**体现了学校对学生驱动、基于热情的学习的承诺。**创新实验室 (I-Labs)** 是思想变为现实的物理连接点。**写作与研究中心 (WRC)** 使学生能够成为强大、有洞察力的研究人员和沟通者。</p>`,

    // STEM Section
    stemTitle: "剖析 STEM 强校",
    stemRankingTitle: "排名悖论",
    stemRank1: "全美第一",
    stemRank1Source: "来源: Niche.com (2024)",
    stemRank1Desc: "衡量综合体验，重视家长/学生评价和大学录取结果。",
    stemRank2: "全美第191",
    stemRank2Source: "来源: Newsweek (2020)",
    stemRank2Desc: "衡量传统的标准化数据，如 AP 分数，这并不能完全体现其“后 AP”模式。",
    stemAdvantageTitle: "“后 AP”优势",
    stemAdvantageDesc: "Nueva 提供超过200门课程，而非标准化的 AP 课程。新生可以学习多元微积分；高年级学生可以进行研究生水平的研究。",
    tableCol1: "典型课程",
    tableCol2: "Nueva 等效课程",
    tableRow1a: "AP 微积分 BC",
    tableRow1b: "微分方程",
    tableRow2a: "AP 物理 C",
    tableRow2b: "量子物理",
    tableRow3a: "AP 生物",
    tableRow3b: "药物设计",
    tableRow4a: "AP 计算机科学",
    tableRow4b: "高级计算机科学项目",

    // Admissions Section
    admissionsTitle: "严峻的考验：锻造创新者",
    admissionsGauntletTitle: "招生考验",
    gauntlet1Title: "1. 认知基线",
    gauntlet1Desc: "韦氏智商评估（130+分）。",
    gauntlet2Title: "2. “创意项目”",
    gauntlet2Desc: "提交原创作品以展示热情。",
    gauntlet3Title: "3. 分析能力",
    gauntlet3Desc: "限时练习以评估思维能力。",
    gauntlet4Title: "4. 综合审查",
    gauntlet4Desc: "面试和推荐信。",
    anatomyTitle: "学生剖析",
    anatomyDesc: "招生过程旨在筛选出能在 Nueva 生态系统中茁壮成长的特质。",
    chartData: {
        labels: ['内在动机', '创造性自信', '情感敏锐度', '协作精神'],
        datasets: [{ label: '学生特质', data: [30, 25, 25, 20], backgroundColor: ['#E9C46A', '#2A9D8F', '#F4A261', '#E76F51'], hoverOffset: 8, borderColor: '#2A363B', borderWidth: 4 }]
    },

    // Comparison Section
    comparisonTitle: "全国格局",
    compTableH1: "指标",
    compTableH2: "Nueva 学校",
    compTableH3: "菲利普斯埃克塞特学院",
    compTableH4: "TJHSST",
    compTableR1H: "核心教学法",
    compTableR1C1: "综合设计思维、社交情感学习和探究式学习。",
    compTableR1C2: "哈克尼斯圆桌法：学生主导、基于讨论的苏格拉底式对话。",
    compTableR1C3: "结构化、加速的、基于实验室的课程，设有高年级研究项目。",
    compTableR2H: "环境",
    compTableR2C1: "协作、富有同情心，培养内在动机。",
    compTableR2C2: "学术严谨、沉浸式、寄宿制，以激烈辩论为中心。",
    compTableR2C3: "预备专业、以实验室为中心、高度专业化和专注。",
    compTableR3H: "主要技能",
    compTableR3C1: "以人为本的创意创新。高情商和高智商的融合。",
    compTableR3C2: "通过文明对话进行批判性分析和清晰论证。",
    compTableR3C3: "先进的科学和工程研究方法。",
    compTableR4H: "理想学生",
    compTableR4C1: "一个在自主性中茁壮成长的天才、有创造力的系统思考者。",
    compTableR4C2: "一个在严谨辩论中茁壮成长的求知欲强的学生。",
    compTableR4C3: "对特定 STEM 领域有深厚热情的学生。",

    // DIY Section
    diyTitle: "打造你自己的 Nueva",
    diyPillar1Title: "支柱一：探究",
    diyPillar2Title: "支柱二：设计思维",
    diyPillar3Title: "支柱三：社交情感学习",
    diyStrategy: "策略：",
    diyOnline: "在线资源：",
    diyBayArea: "湾区资源：",
    diyPillar1Strategy: "通过追求深度、学生主导的项目和大学水平的课程来复制“Quest”项目。目标：创作原创作品。",
    diyPillar1Online1: "Art of Problem Solving (AoPS): 严谨的、基于问题的数学课程。（10-18岁）",
    diyPillar1Online2: "Coursera / edX: 专业课题的大学课程。（13岁以上）",
    diyPillar1Online3: "Lumiere Education: 与博士导师合作的结构化研究项目。（高中）",
    diyPillar1Bay1: "UC Berkeley ATDP: 具有挑战性的暑期课程。（K-11年级）",
    diyPillar1Bay2: "Stanford Pre-Collegiate Studies: 深入研究大学水平课题。（高中）",
    diyPillar1Bay3: "California Academy of Sciences Internship: 真实的科学研究。（高中）",
    diyPillar2Strategy: "通过寻找“在实践中学习”和创造原型的机会来复制创新实验室。专注于动手创造和拥抱失败。",
    diyPillar2Online1: "IDEO U: 在线设计思维课程。（积极的高中生）",
    diyPillar2Online2: "Outschool: 基于项目的课程，如3D打印或Scratch。（3-18岁）",
    diyPillar2Online3: "iD Tech: 旨在构建实体项目的密集型科技夏令营。（7-19岁）",
    diyPillar2Bay1: "The Exploratorium (旧金山): 动手发明的修补工作室。（所有年龄）",
    diyPillar2Bay2: "The Crucible (奥克兰): 工业艺术课程。（8-18岁）",
    diyPillar2Bay3: "Galileo Camps (多地): 专注于创新的夏令营。（学前班至10年级）",
    diyPillar3Strategy: "通过寻求需要团队合作和同理心的体验来复制“挚爱社区”。目标：培养协作的“软技能”。",
    diyPillar3Online1: "Synthesis: 基于团队、基于游戏的问题解决。（8-14岁）",
    diyPillar3Online2: "Outschool: 关于辩论或协作讲故事的直播课程。（5-18岁）",
    diyPillar3Online3: "模拟联合国/模拟法庭: 锻炼谈判和公开演讲技巧的在线俱乐部。（初中/高中）",
    diyPillar3Bay1: "American Conservatory Theater (旧金山): 建立自信和同理心的表演课程。（8-19岁）",
    diyPillar3Bay2: "Bay Area Debate Club (多地): 培养批判性思维的课程和比赛。（初中/高中）",
    diyPillar3Bay3: "SF-Marin Food Bank (旧金山): 培养社区意识的志愿服务。（11岁以上，需成人陪同）",

    // Footer
    footerShareTitle: "分享此分析",
    footerTwitter: "Twitter",
    footerLinkedIn: "LinkedIn",
    footerCopy: "复制链接",
    copySuccess: "链接已复制！",
    footerDisclaimer: "本网站综合了《NUEVA 学校：深度分析报告》的数据。图表由 CHART.JS/HTML/CSS 创建。未使用 SVG/MERMAID JS。"
};
